typography_spectrum: 0.6831663735210896
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#535353'
    - '#b9b9b9'
    - '#343434'
  brandStrength: 0.45937548391520977
  lightness: 0.5541288640815765
  saturation: 0.9627081097569317
  rhythmicContrast: 0.7690157864708453
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.25634
analytics:
  google: null
  facebook: null
  twitter: null
name: onemindfulmoment
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: ONE MINDFUL MOMENT
description: Once Again this builder is AWFUL!
purpose: []
